# Generated by Django 4.2.1 on 2023-07-02 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_name', models.CharField(max_length=30)),
                ('Author', models.CharField(max_length=30)),
                ('Publication_date', models.CharField(max_length=10)),
                ('price', models.FloatField(default=500)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(default='abc.jpg', upload_to='Images')),
                ('cat_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.category')),
            ],
            options={
                'db_table': 'Book',
            },
        ),
    ]
